## Indoor grow tent tensiometer via hx710b (hx711 compat), CCS811/BME280 and (more accurate) scd-40 ##
# https://learn.sparkfun.com/tutorials/esp32-s2-thing-plus-hookup-guide
# TMP117 temperature via https://esphome.io/components/sensor/tmp117.html
# SHT40 temperature/humidity
# CCS811/BME280 environment combo sensor
# BH1750 ambient light sensor - https://esphome.io/components/sensor/bh1750.html
esphome:
  name: indoorgrow
  comment: tensiometer and environmental sensors for an indoor grow tent, under canopy

esp32:
  board: esp32thing_plus

globals:
  - id: open_tube
    type: float
    restore_value: yes
    initial_value: "7777" # measure the open tube pressure and record it here

i2c:
  scan: true
  # labeled as SDA/SCL but also on the Qwiic connector
  sda: GPIO23
  scl: GPIO22


sensor:
  - platform: scd4x
    co2:
      name: "Weed Undercanopy scd-41 CO2"
    temperature:
      name: "Weed Undercanopy scd-41 Temperature"
    humidity:
      name: "Weed Undercanopy scd-41 Humidity"
    ambient_pressure_compensation_source: bme_pressure
    update_interval: 15s
  - platform: hx711
    name: "Indoor Earthbox Tensiometer Tube Pressure"
    unit_of_measurement: hpa
    device_class: "pressure"
    state_class: "measurement"
    # upper right side A5/A0 with usb down
    dout_pin: GPIO4 # A5
    clk_pin: GPIO26  # A0
    gain: 128
    update_interval: 5s
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
  - platform: ccs811
    baseline: 0x98BE # pulled from the logs of the running device after 20-30 minutes
    temperature: bme_temp # use the external temperature sensor to improve these results
    humidity: bme_humidity # same with humidity from the bme
    eco2:
      name: "CCS811 eCO2 Value"
    tvoc:
      name: "CCS811 Total Volatile Organic Compound"
    address: 0x5B
    update_interval: 60s
    # temperature: external temperature sensor ID
  - platform: bme280
    temperature:
      name: "Weed Undercanopy BME280 Temperature"
      id: bme_temp
      oversampling: 16x
    pressure:
      name: "Weed Undercanopy BME280 Pressure"
      id: bme_pressure
    humidity:
      name: "Weed Undercanopy BME280 Humidity"
      id: bme_humidity
    # Address is not default!
    address: 0x77
    update_interval: 15s
  - platform: tmp117
    name: "Weed Undercanopy TMP117 Temperature"
    update_interval: 15s
  - platform: bh1750
    name: "Weed Undercanopy BH1750 Illuminance"
    address: 0x23
    update_interval: 15s
    filters:
      - sliding_window_moving_average:
          window_size: 3
          send_every: 1

wifi:
  fast_connect: True
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain

mqtt:
  broker: '192.168.178.127'
  username: !secret mqtt_username
  password: !secret mqtt_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password
