# multi-zone light controller for a boat

esphome:
  name: litcontrol
  platform: ESP32 
  board: featheresp32

web_server:
  port: 80

prometheus:

# big N position selector switch is wired from a GPIO, through the switch, to ground
binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO13
      inverted: True
      mode: INPUT_PULLUP
    name: "prg1 All Off"
    id: all_off
    on_press:
      then:
        - light.turn_off: zone1
        - light.turn_off: zone2
        - light.turn_off: zone3
        - logger.log: "All Off"
  - platform: gpio
    pin: 
      number: GPIO12
      inverted: True
      mode: INPUT_PULLUP
    name: "prg2 Night Vision"
    id: loggins
    on_press:
      then:
        - light.addressable_set:
            id: zone1
            red: 20%
            green: 0%
            blue: 0%
        - logger.log: "Night Vision"
  - platform: gpio
    pin:
      number: GPIO27
      inverted: True
      mode: INPUT_PULLUP
    name: "prg3 Cozy Firelight"
    id: cozy
    on_press:
      then:
        - light.turn_on:
            id: zone1
            red: 45%
            green: 24%
            blue: 12%
            effect: flicker
        - light.turn_on:
            id: zone2
            red: 45%
            green: 24%
            blue: 12%
            effect: flicker
        - light.turn_on:
            id: zone3
            red: 45%
            green: 24%
            blue: 12%
            effect: flicker
        - logger.log: "Cozy Firelight"
  - platform: gpio
    pin:
      number: GPIO33
      inverted: True
      mode: INPUT_PULLUP
    name: "prg3 Blinding Light"
    id: all_on
    on_press:
      then:
        - light.turn_on:
            id: zone1
            red: 100%
            green: 100%
            blue: 100%
        - light.turn_on:
            id: zone2
            red: 100%
            green: 100%
            blue: 100%
        - light.turn_on:
            id: zone3
            red: 100%
            green: 100%
            blue: 100%
        - logger.log: "Blinding Light"

sensor:
  - platform: uptime
    name: litcontrol Uptime Sensor

light:
  - platform: fastled_clockless
    id: zone1
    name: "Zone 1 - Console Lights"
    color_correct: [50%, 50%, 50%] # never exceed half power
    chipset: WS2812
    pin: GPIO23
    num_leds: 75
    rgb_order: BRG
  - platform: fastled_clockless
    id: zone2
    name: "Zone 2 - Cabin Lights"
    color_correct: [50%, 50%, 50%] # never exceed half power
    chipset: WS2812
    pin: GPIO22
    num_leds: 61
    rgb_order: BRG
  - platform: fastled_clockless
    id: zone3
    name: "Zone 3 - Cockpit Lights"
    color_correct: [50%, 50%, 50%] # never exceed half power
    chipset: WS2812
    pin: GPIO14
    num_leds: 48
    rgb_order: BRG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain

mqtt:
  broker: '192.168.178.127'
  username: !secret mqtt_username
  password: !secret mqtt_password

# Enable logging
logger:

ota:

api:

