# a base m5stack station with a battery, external sht31 and their plant moisture/pump module
# I have the display backlit and somewhat working, but haven't sorted out direction or proper scaling

# borrowed heavily from https://github.com/rasclatt-dot-com/ESP32-Plant-Waterer-for-ESPHome/blob/main/ESPHome-Plant-Waterer.YAML

substitutions:
  name: "m5station"
  friendly_name: "Drying Room M5Stack Station-bat"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: lamont.m5stack_station_bat
    version: "1.0"
  min_version: 2023.5.0

esp32:
  board: m5stack-station
  framework:
    type: arduino

<<: !include .home.yaml

external_components:
  - source: github://pionizer/pionizer-axp192
    components: [axp192]

i2c:
  - id: bus_int
    scan: true
    sda: GPIO21
    scl: GPIO22
  - id: bus_ext
    scan: true
    sda: GPIO32
    scl: GPIO33

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO37
      inverted: true
    name: Button_A
    id: station_button_a
  - platform: gpio
    pin:
      number: GPIO38
      inverted: true
    name: Button_B
    id: station_button_b
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: Button_C
    id: station_button_c
  - platform: template
    name: Soil Moisture
    device_class: moisture
    #Change this value to determine desire wetness of soil
    lambda: |-
      if (id(plant_moisture_percent).state > 35) {
        return true; 
      } else {
        return false; 
      }

display:
  - platform: st7789v
    model: Custom
    height: 135
    width: 240
    offset_height: 0
    offset_width: 0
    #backlight_pin: AXP_LDO3
    cs_pin: GPIO5
    dc_pin: GPIO19
    reset_pin: GPIO15
    lambda: |-
      it.line(0, 0, 50, 50);
      it.print(0, 0, id(roboto), "Hello World!");

font:
  - file: "gfonts://Roboto"
    id: roboto
    size: 20

light:
  - platform: fastled_clockless
    chipset: SK6812
    pin: GPIO4
    num_leds: 7
    rgb_order: GRB
    name: "m5station 7 Lights"
    internal: true
    id: panel_lights
  - platform: partition
    name: "PA1"
    segments:
      - id: panel_lights
        from: 0
        to: 0
  - platform: partition
    name: "PB1"
    segments:
      - id: panel_lights
        from: 1
        to: 1
  - platform: partition
    name: "PC1"
    segments:
      - id: panel_lights
        from: 2
        to: 2
  - platform: partition
    name: "Center"
    segments:
      - id: panel_lights
        from: 3
        to: 3
  - platform: partition
    name: "PC2"
    segments:
      - id: panel_lights
        from: 4
        to: 4
  - platform: partition
    name: "PB2"
    segments:
      - id: panel_lights
        from: 5
        to: 5
  - platform: partition
    name: "PA2"
    segments:
      - id: panel_lights
        from: 6
        to: 6

sensor:
  - platform: adc
    pin: GPIO36
    id: plant_moisture_percent
    name: "m5station plant moisture"
    attenuation: auto
    accuracy_decimals: 0
    unit_of_measurement: "%"
    update_interval: 15s
    icon: mdi:flower
    filters:
      - calibrate_linear:
          - 1.795 -> 100.0
          - 1.43 -> 0.0
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
      - median:
          window_size: 15
          send_every: 7
          send_first_at: 3
  - platform: axp192
    model: m5stickc # turns on LDO3
    i2c_id: bus_int
    address: 0x34
    brightness: 100%
    update_interval: 15s
    battery_level:
      id: "m5_station_battery_level"
      name: "Drying m5station Bat"
  - platform: mpu6886
    address: 0x68
    i2c_id: bus_int
    update_interval: 60s
    accel_x:
      name: "${name} Accel X"
    accel_y:
      name: "${name} Accel Y"
    accel_z:
      name: "${name} Accel z"
    gyro_x:
      name: "${name} Gyro X"
    gyro_y:
      name: "${name} Gyro Y"
    gyro_z:
      name: "${name} Gyro z"
    temperature:
      name: "${name} internal Temperature"
  - platform: ina3221
    address: 0x40
    i2c_id: bus_int
    channel_1:
      shunt_resistance: 0.1 ohm
      current:
        name: "Port A Current"
      power:
        name: "Port A Power"
      bus_voltage:
        name: "Port A Bus Voltage"
      shunt_voltage:
        name: "Port A Shunt Voltage"
    channel_2:
      shunt_resistance: 0.1 ohm
      current:
        name: "Port B1 Current"
      power:
        name: "Port B1 Power"
      bus_voltage:
        name: "Port B1 Bus Voltage"
      shunt_voltage:
        name: "Port B1 Shunt Voltage"
    update_interval: 60s
  - platform: ina3221
    address: 0x41
    i2c_id: bus_int
    channel_1:
      shunt_resistance: 0.1 ohm
      current:
        name: "Port B2 Current"
      power:
        name: "Port B2 Power"
      bus_voltage:
        name: "Port B2 Bus Voltage"
      shunt_voltage:
        name: "Port B2 Shunt Voltage"
    channel_2:
      shunt_resistance: 0.1 ohm
      current:
        name: "Port C1 Current"
      power:
        name: "Port C1 Power"
      bus_voltage:
        name: "Port C1 Bus Voltage"
      shunt_voltage:
        name: "Port C1 Shunt Voltage"
    channel_3:
      shunt_resistance: 0.1 ohm
      current:
        name: "Port C2 Current"
      power:
        name: "Port C2 Power"
      bus_voltage:
        name: "Port C2 Bus Voltage"
      shunt_voltage:
        name: "Port C2 Shunt Voltage"
    update_interval: 60s
  - platform: sht3xd
    i2c_id: bus_ext
    temperature:
      name: "m5station Drying Temperature"
    humidity:
      name: "m5station Drying Humidity"
    update_interval: 15s

switch:
  platform: gpio
  pin: GPIO26
  id: plant_pump
  name: "m5station plant pump"
  icon: mdi:water
  on_turn_on:
    - logger.log: "Pump Turned On!"
    - delay: 30s
    - switch.turn_off: plant_pump
    - logger.log: "Pump Turned Off!"
