esphome:
  name: plants
  platform: esp32
  board: featheresp32

api:

ota:

# some sensors
sensor:
  - platform: adc
    name: Battery
    pin: GPIO35
    attenuation: 11db
    update_interval: 5s
    expire_after: 300s
    accuracy_decimals: 5
  - platform: uptime
    name: Uptime Sensor
    update_interval: 5s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain

mqtt:
  broker: '192.168.178.127'
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: clean

# Enable logging
logger:

