esphomeyaml:
  name: powermeter
  platform: ESP8266
  board: wio_link
  # GPIO15 needs to be on for the grove bus to get power
  on_boot:
    priority: -10
    then:
      - switch.turn_on: 'grove_power_supply'

# Example configuration entry
sensor:
  - platform: dht
    model: DHT11
    pin: GPIO13
    temperature:
      name: "Garage Temperature"
    humidity:
      name: "Garage Humidity"
    update_interval: 15s
  - platform: uptime
    name: powermeter Uptime Sensor
    # I think this is the middle pin
  - platform: pulse_counter
    pin: GPIO12
    unit_of_measurement: 'kW'
    name: 'Power Meter'
    filters:
      - multiply: 0.06

switch:
  - platform: gpio
    pin: GPIO15
    id: 'grove_power_supply'


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain

mqtt:
  broker: '192.168.178.127'
  username: !secret mqtt_username
  password: !secret mqtt_password

# Enable logging
logger:

ota:
