esphome:
  name: snek
  platform: ESP8266
  board: wio_link
  # GPIO15 needs to be on for the grove bus to get power
  on_boot:
    priority: 99
    then:
      - switch.turn_on: 'grove_power_supply'

# Example configuration entry
sensor:
  - platform: dht
    # Digital Port 2
    pin: GPIO13
    temperature:
      name: "Snek midpoint internal ground temperature"
    humidity:
      name: "Snek midpoint internal ground humidity"
    update_interval: 15s
  - platform: dht
    pin: GPIO12
    temperature:
      name: "Snek right internal ground temperature"
    humidity:
      name: "Snek right internal ground humidity"
    update_interval: 15s
  - platform: dht
    pin: GPIO14
    temperature:
      name: "Snek external temperature"
    humidity:
      name: "Snek external humidity"
    update_interval: 15s
  - platform: uptime
    name: Uptime Sensor
  - platform: sht3xd
    temperature:
      name: "Snek internal midpoint temperature"
    humidity:
      name: "Snek internal midpoint humidity"
    address: 0x44
    update_interval: 15s

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: True
  id: bus_a

switch:
  - platform: gpio
    pin: GPIO15
    id: 'grove_power_supply'

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain

api:

# Enable logging
logger:

ota:

