esphome:
  name: testsoil 
  platform: ESP8266
  board: wio_link
  # GPIO15 needs to be on for the grove bus to get power
  on_boot:
    priority: 99
    then:
      - switch.turn_on: 'grove_power_supply'

# Example configuration entry
sensor:
  - platform: uptime
    name: Uptime Sensor
  - platform: adc
    name: moisture
    pin: A0
    update_interval: '10s'
  - platform: uptime
    name: last_update
    update_interval: '10s'
    filters:
      - lambda: return (id(sntp_time).now()).time;
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

switch:
  - platform: gpio
    pin: GPIO15
    id: 'grove_power_supply'

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain

api:

# Enable logging
logger:

ota:

time:
  - platform: sntp
    id: sntp_time
    servers:
      - 192.168.178.1
