substitutions:
  devicename: tipper

esphome:
  name: $devicename
  platform: ESP8266
  board: wio_link
  # GPIO15 needs to be on for the grove bus to get power
  on_boot:
    priority: 99
    then:
      - switch.turn_on: 'grove_power_supply'

# Example configuration entry
sensor:
  - platform: uptime
    name: ${devicename} Uptime Sensor
  - platform: adc
    name: ${devicename} moisture
    pin: A0
    update_interval: '10s'
  - platform: template
    name: ${devicename} last update
    id: template_sens
    update_interval: '10s'
    unit_of_measurement: 's'
    filters:
      - lambda: return (id(sntp_time).now()).time;
  - platform: wifi_signal
    name: "${devicename} WiFi Signal Sensor"
    update_interval: 10s

switch:
  - platform: gpio
    pin: GPIO15
    id: 'grove_power_supply'

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain

mqtt:
  broker: '192.168.178.127'
  username: !secret mqtt_username
  password: !secret mqtt_password

deep_sleep:
  run_duration: 1min
  sleep_duration: 700seconds

# Enable logging
logger:

ota:

time:
  - platform: sntp
    id: sntp_time
    timezone: 'America/Los_Angeles'
    servers:
      - 192.168.178.1
      - 192.168.178.5
