# under cabinet light strip, 100" of PWM controlled LEDs on a 12v 3A power supply
# on a LEDENET Smart WiFi LED Controller: 
# https://www.esphome-devices.com/devices/ledenet-smart-wifi-rgb-ww-cw/
# meant to turn on quickly to a neutral white for cooking
# should automatically dim during plex or low-light situations

substitutions:
  device_name: "undercabinet"
  friendly_name: "Kitchen undercabinet RGB/WW/CW strip"
  cold_temp: 6536 K
  warm_temp: 2000 K

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp8285
  on_boot:
    then:
      - light.turn_on:
          id: ${device_name}
          brightness: 50%
          white: 50%

web_server:
  port: 80

prometheus:
  
sensor:
  - platform: uptime
    name: undercabinet Uptime Sensor

binary_sensor:
  - platform: gpio
    name: "${device_name} Reset Button"
    id: button
    pin:
      number: GPIO0
      inverted: true

status_led:
  pin:
    number: GPIO2
    inverted: true

light:
  - platform: rgbww
    name: ${friendly_name}
    id: ${device_name}
    red: red_channel
    green: green_channel
    blue: blue_channel
    cold_white: cold_white_channel
    warm_white: warm_white_channel
    cold_white_color_temperature: ${cold_temp}
    warm_white_color_temperature: ${warm_temp}
    restore_mode: ALWAYS_ON

output:
  - platform: esp8266_pwm
    id: red_channel
    pin: GPIO14
  - platform: esp8266_pwm
    id: green_channel
    pin: GPIO12
  - platform: esp8266_pwm
    id: blue_channel
    pin: GPIO13
  - platform: esp8266_pwm
    id: cold_white_channel
    pin: GPIO5
  - platform: esp8266_pwm
    id: warm_white_channel
    pin: GPIO15

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain

mqtt:
  broker: '192.168.178.127'
  username: !secret mqtt_username
  password: !secret mqtt_password

# Enable logging
logger:

ota:
  password: !secret ota_password

api:
  reboot_timeout: 0s

